version: '2'
services:
  memcached:
    image: memcached:1.4
    ports:
      - "11212:11211"
    networks:
      - test-network

  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
    ports:
      - "13306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    container_name: mysql
    networks:
       - test-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/var/www/html
    links:
      - web
    container_name: nginx
    networks:
      test-network:
        aliases:
          - genesis.loc
          - genesis-test.loc

  web:
    build: ./php-fpm74
    volumes:
      - ../:/var/www/html
    links:
      - mysql
    environment:
      DATABASE_HOST: 'mysql'
      DATABASE_NAME: 'genesis'
      DATABASE_USER: 'root'
      DATABASE_PASSWORD: 'pass'
    container_name: web
    networks:
      test-network:
        aliases:
          - genesis.loc
          - genesis-test.loc

networks:
  test-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
